import { Inter } from "next/font/google";
import "./globals.css";
import News from "@/components/News";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "X next-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between max-w-6xl mx-auto">
          <div className="hidden sm:inline border-r h-screen">
            <Sidebar></Sidebar>
          </div>
       <div>{children}</div>
        <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
          <div className="sticky top-0 bg-white pt-2">
            <input className="bg-gray-200 border border-gray-200 rounded-full text-sm w-full px-4 py-2" type="text" placeholder="Search"></input>
          </div>
          <News></News>
        </div>
        </div>
        </body>
    </html>
  );
}
